# Generated by Django 3.1.2 on 2020-12-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Level', models.CharField(max_length=3)),
                ('Registration_date', models.DateTimeField(auto_now_add=True)),
                ('Last_login', models.DateTimeField(auto_now_add=True)),
                ('XP', models.CharField(max_length=3)),
            ],
        ),
    ]
