# Generated by Django 3.1.2 on 2020-12-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Level', models.CharField(max_length=50)),
                ('HP', models.CharField(max_length=50)),
                ('DMG', models.CharField(max_length=50)),
                ('XP', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Power', models.CharField(max_length=5)),
                ('Evasion_rate', models.CharField(max_length=50)),
                ('Level_requirement', models.CharField(max_length=50)),
                ('Cooldown', models.CharField(max_length=50)),
                ('File_name', models.CharField(max_length=500)),
            ],
        ),
    ]
