# Generated by Django 3.1.2 on 2020-12-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mobs_spells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Last_login',
        ),
    ]
