# Generated by Django 3.1.4 on 2020-12-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201230_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=1)),
                ('dmg', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_spell', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=3000)),
                ('power', models.IntegerField()),
                ('evasion_rate', models.IntegerField()),
                ('level_requirement', models.IntegerField(default=1)),
                ('cooldown', models.IntegerField()),
                ('file_name', models.CharField(max_length=300)),
            ],
        ),
    ]
