# Generated by Django 3.1.4 on 2020-12-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201230_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='account',
            name='spellA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='spellB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='spellC',
            field=models.IntegerField(default=0),
        ),
    ]
